site_name: libvirt-python
site_url: https://libvirt.org
repo_url: https://github.com/rst0git/libvirt-python-docs

nav:
  - Capabilities: capabilities.md
  - Connections: connections.md
  - Device configuration: device-config.md
  - Domain configuration: domain-config.md
  - Host information: host-info.md
  - Lifecycle control: lifecycle-control.md
  - Live configuration change: live-config-change.md
  - Monitoring performance: monitoring-performance.md
  - Storage pools: storage-pools.md
  - URI formats: uri-format.md
theme:
  name: readthedocs
  favicon: img/favicon.ico
  navigation_depth: 2

extra_css:
    - css/extra.css

markdown_extensions:
    - admonition
    - toc:
        permalink: true
    - footnotes
    - meta